<?php

declare(strict_types=1);

/**
 * Catálogo de métricas por área (día / año).
 * Todo se lee siempre sobre el año seleccionado; los valores vivos se calculan aparte.
 */
final class MetricCatalog
{
    /**
     * @return array<string, array{name:string, day:list<string>, year:list<string>, notes?:string}>
     */
    public static function byArea(): array
    {
        return [
            'annual_educacion' => [
                'name' => 'Educación',
                'day' => [
                    'Minutos y horas de estudio',
                    'Páginas leídas',
                    'Minutos de lectura',
                    'Lecciones o módulos completados',
                    'Sesiones de idiomas',
                    'Minutos por idioma',
                    'Palabras nuevas aprendidas',
                    'Acciones educativas completadas',
                    'Progreso diario de objetivos educativos',
                ],
                'year' => [
                    'Horas totales y promedio de estudio',
                    'Días con actividad educativa',
                    'Libros terminados',
                    'Cumplimiento de la meta anual de lectura',
                    'Páginas leídas',
                    'Cursos y módulos completados',
                    'Materias cursadas y aprobadas',
                    'Exámenes rendidos y aprobados',
                    'Promedio de calificaciones',
                    'Certificaciones obtenidas',
                    'Nivel alcanzado en cada idioma',
                    'Objetivos educativos completados',
                    'Comparación con el año anterior',
                ],
            ],
            'annual_trabajo' => [
                'name' => 'Trabajo',
                'day' => [
                    'Minutos y horas de trabajo enfocado',
                    'Sesiones de trabajo profundo',
                    'Acciones laborales planificadas',
                    'Acciones laborales completadas',
                    'Porcentaje del plan diario completado',
                    'Reuniones realizadas',
                    'Tiempo dedicado a reuniones',
                    'Interrupciones',
                    'Progreso diario de objetivos laborales',
                    'Nivel de energía laboral',
                ],
                'year' => [
                    'Horas de trabajo enfocado',
                    'Días con actividad laboral',
                    'Objetivos laborales completados',
                    'Hitos profesionales alcanzados',
                    'Postulaciones realizadas',
                    'Entrevistas laborales',
                    'Ofertas laborales',
                    'Nuevos trabajos, roles o responsabilidades',
                    'Meses de continuidad en cada trabajo',
                    'Horas de docencia',
                    'Nuevos contactos profesionales',
                    'Cumplimiento del plan laboral anual',
                    'Comparación con el año anterior',
                ],
            ],
            'annual_marca' => [
                'name' => 'Marca personal',
                'day' => [
                    'Palabras escritas',
                    'Páginas escritas',
                    'Minutos de escritura',
                    'Publicaciones en LinkedIn',
                    'Publicaciones en X',
                    'Commits públicos en GitHub',
                    'Minutos dedicados a contenido',
                    'Ideas registradas',
                    'Borradores completados',
                    'Piezas terminadas',
                    'Progreso diario de objetivos de marca personal',
                ],
                'year' => [
                    'Artículos publicados',
                    'Newsletters enviados',
                    'Episodios de podcast publicados',
                    'Videos publicados',
                    'Publicaciones por canal',
                    'Días y semanas con publicaciones',
                    'Racha de publicación',
                    'Palabras, páginas y capítulos escritos',
                    'Libros publicados',
                    'Proyectos públicos en GitHub',
                    'Suscriptores y seguidores',
                    'Crecimiento anual de audiencia',
                    'Impresiones',
                    'Interacciones',
                    'Visitas al sitio o blog',
                    'Aperturas y clics del newsletter',
                    'Objetivos de marca personal completados',
                    'Comparación con el año anterior',
                ],
            ],
            'annual_finanzas' => [
                'name' => 'Finanzas',
                'notes' => 'LifeQuest mide objetivos financieros simples. Detalle monetario en Patrium. No calcula saldos, presupuestos ni patrimonio.',
                'day' => [
                    'Acciones completadas para avanzar un objetivo financiero',
                    'Cambio manual de progreso',
                    'Días desde la última actualización',
                    'Acceso directo a Patrium',
                ],
                'year' => [
                    'Objetivos financieros planificados',
                    'Objetivos activos',
                    'Objetivos completados',
                    'Objetivos pausados o vencidos',
                    'Progreso de cada objetivo',
                    'Porcentaje de objetivos completados',
                    'Objetivos completados dentro de la fecha',
                    'Meses con actualización de progreso',
                    'Comparación con el año anterior',
                    'Referencia al resultado detallado en Patrium',
                ],
            ],
            'annual_salud' => [
                'name' => 'Salud',
                'day' => [
                    'Entrenamiento realizado',
                    'Minutos de entrenamiento',
                    'Pasos',
                    'Distancia caminada o corrida',
                    'Volumen de entrenamiento de fuerza',
                    'Horas de sueño',
                    'Calidad del sueño',
                    'Consumo de agua',
                    'Peso, cuando corresponda',
                    'Nivel de energía',
                    'Estado de ánimo',
                    'Nivel de estrés',
                    'Cumplimiento de medicación',
                    'Día sin alcohol',
                    'Día sin gaseosa',
                    'Día sin azúcar',
                    'Día sin golosinas',
                    'Día sin cigarrillo',
                    'Día sin drogas recreativas',
                    'Progreso diario de objetivos de salud',
                ],
                'year' => [
                    'Sesiones de entrenamiento',
                    'Horas de entrenamiento',
                    'Días activos',
                    'Promedio de pasos',
                    'Distancia acumulada',
                    'Evolución del peso',
                    'Evolución de otras mediciones corporales',
                    'Promedio y tendencia del sueño',
                    'Días de abstinencia por consumo',
                    'Consultas médicas realizadas',
                    'Estudios médicos completados',
                    'Procedimientos odontológicos',
                    'Sesiones de terapia',
                    'Objetivos de salud completados',
                    'Comparación con el año anterior',
                ],
            ],
            'annual_proyectos' => [
                'name' => 'Proyectos',
                'day' => [
                    'Minutos y horas por proyecto',
                    'Acciones planificadas',
                    'Acciones completadas',
                    'Hitos completados',
                    'Cambio diario de progreso',
                    'Commits vinculados',
                    'Issues vinculados',
                    'Pull requests vinculados',
                    'Errores encontrados',
                    'Errores resueltos',
                    'Decisiones tomadas',
                    'Cambios de alcance',
                    'Días desde la última actividad',
                ],
                'year' => [
                    'Proyectos planificados',
                    'Proyectos iniciados',
                    'Proyectos completados',
                    'Proyectos activos',
                    'Proyectos pausados',
                    'Proyectos cancelados',
                    'Proyectos vencidos',
                    'Proyectos completados dentro de su semana',
                    'Tasa anual de finalización',
                    'Horas totales dedicadas',
                    'Duración planificada frente a duración real',
                    'Hitos completados',
                    'Errores encontrados y resueltos',
                    'Despliegues realizados',
                    'Versiones publicadas',
                    'Documentación generada',
                    'Casos de estudio generados',
                    'Semanas consecutivas entregando proyectos',
                    'Proyectos por área de impacto',
                    'Comparación con el año anterior',
                ],
            ],
        ];
    }

    /** @return list<string> */
    public static function consolidated(): array
    {
        return [
            'Actividad del día por área',
            'Progreso anual por área',
            'Objetivos activos y completados',
            'Variación contra el período anterior',
            'Días con actividad',
            'Distribución del tiempo',
            'Área con mayor actividad',
            'Área con menor actividad',
            'Balance entre las seis áreas',
            'Cantidad de áreas activas por día y mes',
            'Relación entre Educación, Trabajo, Marca personal y Proyectos',
            'Relación entre Salud y el rendimiento de las demás áreas',
        ];
    }
}
